// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/signaling.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// https://pkg.go.dev/github.com/pion/webrtc/v3#SDPType
type SessionDescription_SDPType int32

const (
	SessionDescription_SDP_TYPE_UNSPECIFIED SessionDescription_SDPType = 0
	SessionDescription_offer                SessionDescription_SDPType = 1
	SessionDescription_SDP_TYPE_OFFER       SessionDescription_SDPType = 1
	SessionDescription_pranswer             SessionDescription_SDPType = 2
	SessionDescription_SDP_TYPE_PRANSWER    SessionDescription_SDPType = 2
	SessionDescription_answer               SessionDescription_SDPType = 3
	SessionDescription_SDP_TYPE_ANSWER      SessionDescription_SDPType = 3
	SessionDescription_rollback             SessionDescription_SDPType = 4
	SessionDescription_SDP_TYPE_ROLLBACK    SessionDescription_SDPType = 4
)

// Enum value maps for SessionDescription_SDPType.
var (
	SessionDescription_SDPType_name = map[int32]string{
		0: "SDP_TYPE_UNSPECIFIED",
		1: "offer",
		// Duplicate value: 1: "SDP_TYPE_OFFER",
		2: "pranswer",
		// Duplicate value: 2: "SDP_TYPE_PRANSWER",
		3: "answer",
		// Duplicate value: 3: "SDP_TYPE_ANSWER",
		4: "rollback",
		// Duplicate value: 4: "SDP_TYPE_ROLLBACK",
	}
	SessionDescription_SDPType_value = map[string]int32{
		"SDP_TYPE_UNSPECIFIED": 0,
		"offer":                1,
		"SDP_TYPE_OFFER":       1,
		"pranswer":             2,
		"SDP_TYPE_PRANSWER":    2,
		"answer":               3,
		"SDP_TYPE_ANSWER":      3,
		"rollback":             4,
		"SDP_TYPE_ROLLBACK":    4,
	}
)

func (x SessionDescription_SDPType) Enum() *SessionDescription_SDPType {
	p := new(SessionDescription_SDPType)
	*p = x
	return p
}

func (x SessionDescription_SDPType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionDescription_SDPType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_signaling_proto_enumTypes[0].Descriptor()
}

func (SessionDescription_SDPType) Type() protoreflect.EnumType {
	return &file_proto_signaling_proto_enumTypes[0]
}

func (x SessionDescription_SDPType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionDescription_SDPType.Descriptor instead.
func (SessionDescription_SDPType) EnumDescriptor() ([]byte, []int) {
	return file_proto_signaling_proto_rawDescGZIP(), []int{0, 0}
}

// https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription
type SessionDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type SessionDescription_SDPType `protobuf:"varint,1,opt,name=type,proto3,enum=SessionDescription_SDPType" json:"type,omitempty"`
	// Follows the format specified here: https://tools.ietf.org/html/rfc4566#section-5
	Sdp string `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
}

func (x *SessionDescription) Reset() {
	*x = SessionDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_signaling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDescription) ProtoMessage() {}

func (x *SessionDescription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signaling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDescription.ProtoReflect.Descriptor instead.
func (*SessionDescription) Descriptor() ([]byte, []int) {
	return file_proto_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SessionDescription) GetType() SessionDescription_SDPType {
	if x != nil {
		return x.Type
	}
	return SessionDescription_SDP_TYPE_UNSPECIFIED
}

func (x *SessionDescription) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

var File_proto_signaling_proto protoreflect.FileDescriptor

var file_proto_signaling_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x02, 0x0a, 0x12, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x44, 0x50, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x64,
	0x70, 0x22, 0xb1, 0x01, 0x0a, 0x07, 0x53, 0x44, 0x50, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x14, 0x53, 0x44, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x44, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4f,
	0x46, 0x46, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x70, 0x72, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x44, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x52, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x44, 0x50, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08,
	0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x44,
	0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f, 0x4c, 0x4c, 0x42, 0x41, 0x43, 0x4b, 0x10,
	0x04, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x7a, 0x6f, 0x6f, 0x6d, 0x67, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_signaling_proto_rawDescOnce sync.Once
	file_proto_signaling_proto_rawDescData = file_proto_signaling_proto_rawDesc
)

func file_proto_signaling_proto_rawDescGZIP() []byte {
	file_proto_signaling_proto_rawDescOnce.Do(func() {
		file_proto_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_signaling_proto_rawDescData)
	})
	return file_proto_signaling_proto_rawDescData
}

var file_proto_signaling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_signaling_proto_goTypes = []interface{}{
	(SessionDescription_SDPType)(0), // 0: SessionDescription.SDPType
	(*SessionDescription)(nil),      // 1: SessionDescription
}
var file_proto_signaling_proto_depIdxs = []int32{
	0, // 0: SessionDescription.type:type_name -> SessionDescription.SDPType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_signaling_proto_init() }
func file_proto_signaling_proto_init() {
	if File_proto_signaling_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_signaling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_signaling_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_signaling_proto_goTypes,
		DependencyIndexes: file_proto_signaling_proto_depIdxs,
		EnumInfos:         file_proto_signaling_proto_enumTypes,
		MessageInfos:      file_proto_signaling_proto_msgTypes,
	}.Build()
	File_proto_signaling_proto = out.File
	file_proto_signaling_proto_rawDesc = nil
	file_proto_signaling_proto_goTypes = nil
	file_proto_signaling_proto_depIdxs = nil
}
