/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.input.InputEvent', null, global);
goog.exportSymbol('proto.input.KeyPressEvent', null, global);
goog.exportSymbol('proto.input.KeyPressEvent.Direction', null, global);
goog.exportSymbol('proto.input.KeyPressEvent.Key', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.input.InputEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.input.InputEvent.oneofGroups_);
};
goog.inherits(proto.input.InputEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.input.InputEvent.displayName = 'proto.input.InputEvent';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.input.InputEvent.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.input.InputEvent.EventCase = {
  EVENT_NOT_SET: 0,
  KEY_PRESS_EVENT: 1
};

/**
 * @return {proto.input.InputEvent.EventCase}
 */
proto.input.InputEvent.prototype.getEventCase = function() {
  return /** @type {proto.input.InputEvent.EventCase} */(jspb.Message.computeOneofCase(this, proto.input.InputEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.input.InputEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.input.InputEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.input.InputEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.input.InputEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    keyPressEvent: (f = msg.getKeyPressEvent()) && proto.input.KeyPressEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.input.InputEvent}
 */
proto.input.InputEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.input.InputEvent;
  return proto.input.InputEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.input.InputEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.input.InputEvent}
 */
proto.input.InputEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.input.KeyPressEvent;
      reader.readMessage(value,proto.input.KeyPressEvent.deserializeBinaryFromReader);
      msg.setKeyPressEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.input.InputEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.input.InputEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.input.InputEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.input.InputEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeyPressEvent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.input.KeyPressEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional KeyPressEvent key_press_event = 1;
 * @return {?proto.input.KeyPressEvent}
 */
proto.input.InputEvent.prototype.getKeyPressEvent = function() {
  return /** @type{?proto.input.KeyPressEvent} */ (
    jspb.Message.getWrapperField(this, proto.input.KeyPressEvent, 1));
};


/** @param {?proto.input.KeyPressEvent|undefined} value */
proto.input.InputEvent.prototype.setKeyPressEvent = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.input.InputEvent.oneofGroups_[0], value);
};


proto.input.InputEvent.prototype.clearKeyPressEvent = function() {
  this.setKeyPressEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.input.InputEvent.prototype.hasKeyPressEvent = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.input.KeyPressEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.input.KeyPressEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.input.KeyPressEvent.displayName = 'proto.input.KeyPressEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.input.KeyPressEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.input.KeyPressEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.input.KeyPressEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.input.KeyPressEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    direction: jspb.Message.getFieldWithDefault(msg, 1, 0),
    key: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.input.KeyPressEvent}
 */
proto.input.KeyPressEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.input.KeyPressEvent;
  return proto.input.KeyPressEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.input.KeyPressEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.input.KeyPressEvent}
 */
proto.input.KeyPressEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.input.KeyPressEvent.Direction} */ (reader.readEnum());
      msg.setDirection(value);
      break;
    case 2:
      var value = /** @type {!proto.input.KeyPressEvent.Key} */ (reader.readEnum());
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.input.KeyPressEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.input.KeyPressEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.input.KeyPressEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.input.KeyPressEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDirection();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getKey();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.input.KeyPressEvent.Direction = {
  DIRECTION_UNSPECIFIED: 0,
  DIRECTION_UP: 1,
  DIRECTION_DOWN: 2
};

/**
 * @enum {number}
 */
proto.input.KeyPressEvent.Key = {
  KEY_UNSPECIFIED: 0,
  KEY_ARROW_UP: 1,
  KEY_ARROW_DOWN: 2,
  KEY_ARROW_LEFT: 3,
  KEY_ARROW_RIGHT: 4,
  KEY_SPACE: 5,
  KEY_KEY_A: 6,
  KEY_KEY_S: 7,
  KEY_KEY_D: 8
};

/**
 * optional Direction direction = 1;
 * @return {!proto.input.KeyPressEvent.Direction}
 */
proto.input.KeyPressEvent.prototype.getDirection = function() {
  return /** @type {!proto.input.KeyPressEvent.Direction} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.input.KeyPressEvent.Direction} value */
proto.input.KeyPressEvent.prototype.setDirection = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Key key = 2;
 * @return {!proto.input.KeyPressEvent.Key}
 */
proto.input.KeyPressEvent.prototype.getKey = function() {
  return /** @type {!proto.input.KeyPressEvent.Key} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.input.KeyPressEvent.Key} value */
proto.input.KeyPressEvent.prototype.setKey = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


goog.object.extend(exports, proto.input);
